services:
  superbanner.grid.banner_grid_factory:
    class: 'Superbanner\Grid\Definition\Factory\BannerGrid'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true


  superbanner.grid.banner_grid:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@superbanner.grid.banner_grid_factory' # our definition factory
      - '@prestashop.core.grid.definition.factory.abstract_grid_definition'              # our data factory
      - '@prestashop.core.grid.filter.form_factory'                            # core service needed by grid factory
      - '@prestashop.core.hook.dispatcher'                                     # core service needed by grid factory