services:
  superbanner.grid.banner_grid_factory:
    class: 'Superbanner\Grid\Definition\Factory\BannerGrid'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true

  superbanner.grid.query.banner_query_builder:
    class: 'Superbanner\Grid\Query\BannerBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true

  superbanner.grid.data.factory.superbanner_data_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory'
    arguments:
      - '@superbanner.grid.query.banner_query_builder' # service id of our query builder
      - '@prestashop.core.hook.dispatcher' # every doctrine query builder needs the hook dispatcher
      - '@prestashop.core.grid.query.doctrine_query_parser' # parser to get the raw SQL query
      - 'superbanner' # this should match your grid id, in our case it's "products"

  superbanner.grid.banner_grid:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@superbanner.grid.banner_grid_factory'                         # our definition factory
      - '@superbanner.grid.data.factory.superbanner_data_factory'       # our data factory
      - '@prestashop.core.grid.filter.form_factory'                     # core service needed by grid factory
      - '@prestashop.core.hook.dispatcher'                              # core service needed by grid factory


